on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # https://crontab.guru/every-hour

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@0da8b0cd8bb013041bad4f818c2790fa3253efb1 # v36.1.1
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: renovate-config.js
          useSlim: false
          token: ${{ secrets.RENOVATE_TOKEN }}
