on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@0da8b0cd8bb013041bad4f818c2790fa3253efb1 # v36.1.1
        with:
          configurationFile: renovate-config.js
          useSlim: false
          token: ${{ secrets.RENOVATE_TOKEN }}
