on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # https://crontab.guru/every-hour

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.0
        with:
          configurationFile: renovate-config.js
          useSlim: false
          token: ${{ secrets.RENOVATE_TOKEN }}
