on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # https://crontab.guru/every-hour

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@aa150c86873c3e1326734d9c1390064fbc646148 # v36.0.0
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: renovate-config.js
          useSlim: false
          token: ${{ secrets.RENOVATE_TOKEN }}
